name: Run Jarvis Backend

on:
  push:
    branches: [ main ]

jobs:
  run_jarvis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Jarvis
      run: |
        python -c "import requests; print('Jarvis backend is running...')"
